#!/usr/bin/env python3
"""Regenerate the archive + SEO artifacts for itshouldwork.org.

Single source of truth = git history of photo.json. Every commit that changed
photo.json contributed one photo-of-the-day; we extract each one's image into
archive/ and build history.json. Idempotent: safe to run after every scout
publish (locally or in CI). Also refreshes the per-photo SEO block in index.html
and regenerates sitemap.xml from the current pick.
"""
import json
import os
import subprocess
import html

DOMAIN = "https://itshouldwork.org"
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(REPO)


def git_text(*args):
    return subprocess.run(["git", *args], capture_output=True, text=True).stdout


def git_bytes(*args):
    return subprocess.run(["git", *args], capture_output=True).stdout


def build_archive():
    """Extract every past photo from git history into archive/, return entries (newest first)."""
    os.makedirs("archive", exist_ok=True)
    commits = git_text("log", "--format=%H", "--reverse", "--", "photo.json").split()
    entries, seen = [], set()
    for c in commits:
        raw = git_text("show", f"{c}:photo.json")
        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            continue
        fname = data.get("file", "photo.jpg")
        ext = os.path.splitext(fname)[1] or ".jpg"
        blob = git_text("rev-parse", f"{c}:{fname}").strip()
        if not blob or blob in seen:
            continue  # skip missing images and identical re-commits
        seen.add(blob)
        aid = blob[:10]
        date = data.get("date", "")
        arch_path = f"archive/{date}-{aid}{ext}"
        if not os.path.exists(arch_path):
            img = git_bytes("show", f"{c}:{fname}")
            if len(img) < 1000:
                continue
            with open(arch_path, "wb") as f:
                f.write(img)
        entry = {k: data.get(k, "") for k in
                 ("date", "alt", "source", "credit", "license", "story", "why_funny")}
        entry["id"] = aid
        entry["file"] = arch_path
        entries.append(entry)
    entries.reverse()  # newest first
    with open("history.json", "w") as f:
        json.dump({"count": len(entries), "photos": entries}, f, indent=2)
        f.write("\n")
    return entries


def current_pick():
    with open("photo.json") as f:
        return json.load(f)


def refresh_index_seo(pick):
    """Replace the auto-generated SEO block in index.html with tags for the current pick."""
    desc = (pick.get("story") or pick.get("alt") or "").strip()
    desc = " ".join(desc.split())
    if len(desc) > 157:
        desc = desc[:157].rsplit(" ", 1)[0].rstrip(" ,.;:—-") + "…"
    title = "It Should Work"
    img = f"{DOMAIN}/photo.jpg?v={pick.get('date', '')}"
    alt = pick.get("alt", "Photo of the day")
    e = html.escape
    block = f"""<!-- SEO:BEGIN (auto-generated by agent/build-site.py — do not edit by hand) -->
  <meta name="description" content="{e(desc)}">
  <link rel="canonical" href="{DOMAIN}/">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="It Should Work">
  <meta property="og:url" content="{DOMAIN}/">
  <meta property="og:title" content="{e(title)}">
  <meta property="og:description" content="{e(desc)}">
  <meta property="og:image" content="{e(img)}">
  <meta property="og:image:alt" content="{e(alt)}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{e(title)}">
  <meta name="twitter:description" content="{e(desc)}">
  <meta name="twitter:image" content="{e(img)}">
  <!-- SEO:END -->"""
    with open("index.html") as f:
        src = f.read()
    import re
    new = re.sub(r"<!-- SEO:BEGIN.*?<!-- SEO:END -->", block, src, flags=re.DOTALL)
    if new != src:
        with open("index.html", "w") as f:
            f.write(new)


def write_sitemap(pick):
    lastmod = pick.get("date", "")
    urls = [("/", lastmod, "daily"), ("/archive.html", lastmod, "daily")]
    body = "".join(
        f"  <url><loc>{DOMAIN}{loc}</loc>"
        + (f"<lastmod>{mod}</lastmod>" if mod else "")
        + f"<changefreq>{freq}</changefreq></url>\n"
        for loc, mod, freq in urls
    )
    with open("sitemap.xml", "w") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n'
                '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
                + body + "</urlset>\n")


def main():
    build_archive()
    pick = current_pick()
    refresh_index_seo(pick)
    write_sitemap(pick)
    print("build-site: archive + history.json + sitemap.xml + index SEO regenerated")


if __name__ == "__main__":
    main()
